apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavendeployment
  namespace: mobackns
  labels:
    app: mavenapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      labels:
        app: mavenapp
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: mavenappcontainer
          image: 087770005543.dkr.ecr.ap-south-1.amazonaws.com/maven:3
          ports:
            - containerPort: 8080
          resources:
            requests: 
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
