apiVersion: v1
kind: Service
metadata:
  name: mavensvc
  namespace: mobackns
spec:
  selector:
    app: mavenapp
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30400