name: Helm Chart Publish JFrog
run-name: Helm_jfrog_${{ inputs.environment }}_${{ inputs.region }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: dev
        options:
          - dev
          - qa
          - stg
          - prd

      region:
        type: choice
        description: 'AWS Region'
        required: true
        default: us-east-1
        options:
          - us-east-1
          - us-west-2

      chart_version:
        type: string
        description: 'Helm Chart Version (e.g. 1.0.1)'
        required: true

      chart_directory:
        type: string
        description: 'Helm Chart Directory (e.g. alb-ingress)'
        required: true

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          mkdir -p packaged
          helm dependency update ${{ inputs.chart_directory }}
          helm lint ${{ inputs.chart_directory }}
          helm package ${{ inputs.chart_directory }} \
            --version ${{ inputs.chart_version }} \
            --destination packaged

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/

      - name: Configure JFrog CLI
        env:
          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          jfrog config add jfrog-server \
            --url=$ARTIFACTORY_URL \
            --user=$ARTIFACTORY_USERNAME \
            --password=$ARTIFACTORY_PASSWORD \
            --interactive=false

      - name: Push Helm Chart to JFrog
        run: |
          CHART_FILE="packaged/${{ inputs.chart_directory }}-${{ inputs.chart_version }}.tgz"
          jfrog rt upload "$CHART_FILE" "helm-charts-${{ inputs.environment }}/${{ inputs.chart_directory }}/"

      - name: Cleanup JFrog CLI Config
        run: jfrog config remove jfrog-server
