name: Helm Chart Publish jfrog
run-name: Helm_jfrog_${{ inputs.environment }}_${{ inputs.region }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: dev
        options:
          - dev
          - qa
          - stg
          - prd

      region:
        type: choice
        description: 'AWS Region'
        required: true
        default: us-east-1
        options:
          - us-east-1
          - us-west-2

      chart_version:
        type: string
        description: 'Helm Chart Version (e.g. a1b2c3d)'
        required: true

      chart_directory:
        type: string
        description: 'Helm Chart Directory (e.g. eks-custom)'
        required: true

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          helm dependency update ${{ inputs.chart_directory }}
          helm lint ${{ inputs.chart_directory }}
          helm package ${{ inputs.chart_directory }} --version ${{ inputs.chart_version }} --destination packaged

      - name: Publish to JFrog Artifactory
        env:
          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY }}
          ARTIFACTORY_REPO: helm-charts
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          CHART_NAME="${{ inputs.chart_directory }}"
          ENV="${{ inputs.environment }}"
          VERSION="${{ inputs.chart_version }}"
          FILE_NAME="${CHART_NAME}-${VERSION}.tgz"
          TARGET_PATH="${ARTIFACTORY_REPO}/${CHART_NAME}-${ENV}/${FILE_NAME}"

          curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
            -T packaged/${FILE_NAME} \
            "$ARTIFACTORY_URL/$TARGET_PATH"
