name: Helm Chart Publish jfrog
run-name: Helm_jfrog_${{ inputs.environment }}_${{ inputs.region }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: dev
        options:
          - dev
          - qa
          - stg
          - prd

      region:
        type: choice
        description: 'AWS Region'
        required: true
        default: us-east-1
        options:
          - us-east-1
          - us-west-2

      chart_version:
        type: string
        description: 'Helm Chart Version (e.g. 1.0.1)'
        required: true

      chart_directory:
        type: string
        description: 'Helm Chart Directory (e.g. alb-ingress)'
        required: true

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install Helm Push Plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push.git

      - name: Package Helm Chart
        run: |
          mkdir -p packaged
          helm dependency update ${{ inputs.chart_directory }}
          helm lint ${{ inputs.chart_directory }}
          helm package ${{ inputs.chart_directory }} --version ${{ inputs.chart_version }} --destination packaged

      - name: Rename Helm chart with expected filename
        run: |
          ORIGINAL_FILE=$(ls packaged/*.tgz)
          mv "$ORIGINAL_FILE" "packaged/${{ inputs.chart_directory }}-${{ inputs.chart_version }}.tgz"
          echo "Renamed $ORIGINAL_FILE to packaged/${{ inputs.chart_directory }}-${{ inputs.chart_version }}.tgz"

      - name: Add JFrog Helm Repo
        env:
          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          helm repo add jfrog-repo $ARTIFACTORY_URL/helm-charts-${{ inputs.chart_directory }}-${{ inputs.environment }} \
            --username $ARTIFACTORY_USERNAME \
            --password $ARTIFACTORY_PASSWORD

      - name: Push Chart to JFrog
        run: |
          CHART_NAME="${{ inputs.chart_directory }}"
          VERSION="${{ inputs.chart_version }}"
          helm push packaged/${CHART_NAME}-${VERSION}.tgz jfrog-repo
