name: Helm Chart Publish JFrog
run-name: Helm_jfrog_${{ inputs.environment }}_${{ inputs.region }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: dev
        options:
          - dev
          - qa
          - stg
          - prd

      region:
        type: choice
        description: 'AWS Region'
        required: true
        default: us-east-1
        options:
          - us-east-1
          - us-west-2

      chart_version:
        type: string
        description: 'Helm Chart Version (e.g. 1.0.1)'
        required: true

      chart_directory:
        type: string
        description: 'alb-ingress'
        required: true

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest

    env:
      JFROG_URL: ${{ vars.ARTIFACTORY }}
      JFROG_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      JFROG_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      HELM_REPO_KEY:  helm-charts-${{ inputs.environment }}  # e.g., helm-charts-dev

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Lint and Package Helm Chart
        run: |
          mkdir -p packaged
          helm dependency update "${{ inputs.chart_directory }}"
          helm lint "${{ inputs.chart_directory }}"
          helm package "${{ inputs.chart_directory }}" \
            --version "${{ inputs.chart_version }}" \
            --destination packaged
          ls -l packaged

      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh

      - name: Configure JFrog CLI
        run: |
          ./jfrog config add jfrog-server \
            --url="${JFROG_URL}" \
            --user="${JFROG_USERNAME}" \
            --password="${JFROG_PASSWORD}" \
            --interactive=false

      - name: Upload Helm Chart to JFrog
        run: |
          CHART_PACKAGE="packaged/${{ inputs.chart_directory }}-${{ inputs.chart_version }}.tgz"
          echo "Uploading $CHART_PACKAGE to $HELM_REPO_KEY/"
          ./jfrog rt upload "$CHART_PACKAGE" "${HELM_REPO_KEY}/${{ inputs.chart_directory }}-${{ inputs.chart_version }}/" --server-id=jfrog-server


      - name: Cleanup JFrog Config
        run: |
          ./jfrog config remove jfrog-server
