name: Helm Chart Publish
run-name: Helm_${{ inputs.environment }}_${{ inputs.region }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: dev
        options:
          - dev
          - qa
          - stg
          - prd

      region:
        type: choice
        description: 'AWS Region'
        required: true
        default: us-east-1
        options:
          - us-east-1
          - eu-central-1
          - eu-west-1
          - us-west-2
          - ap-southeast-2
          - ap-south-1

      helmChartPath:
        description: 'Path to the Helm chart'
        default: 'alb-ingress'
        type: string

      isHelmChartPush:
        description: 'Whether to push the Helm chart to ECR'
        default: true
        type: boolean

jobs:
  helm-publish:
    name: Build and Push Helm Chart
    runs-on: [self-hosted, Linux, X64, tar-runner]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.region }}
          role-skip-session-tagging: true
          role-duration-seconds: 1200

      - name: Set ECR variables and login to Helm registry
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          export ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${{ inputs.region }}.amazonaws.com"
          export REPO_NAME="helm-${{ inputs.helmChartPath }}-${{ inputs.environment }}"
          export ECR_URI="oci://${ECR_REGISTRY}/${REPO_NAME}"

          echo "ECR_REGISTRY=${ECR_REGISTRY}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "ECR_URI=${ECR_URI}" >> $GITHUB_ENV

          # Create ECR repository if it doesn't exist
          aws ecr describe-repositories --repository-names "${REPO_NAME}" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "${REPO_NAME}"

          # Login to Helm OCI registry
          aws ecr get-login-password --region ${{ inputs.region }} | \
            helm registry login --username AWS --password-stdin "${ECR_REGISTRY}"

      - name: Package Helm chart
        id: helm-package
        run: |
          helm dependency update "${{ inputs.helmChartPath }}"
          helm package "${{ inputs.helmChartPath }}" --destination .
          CHART_PACKAGE=$(ls *.tgz)
          echo "CHART_PACKAGE=${CHART_PACKAGE}" >> $GITHUB_ENV
      
      - name: Push Helm chart to ECR
        if: ${{ inputs.isHelmChartPush }}
        run: |
          echo "Pushing Helm chart to: ${ECR_URI}"
          # Rename the package to match exactly your ECR repo name
          NEW_NAME="helm-alb-ingress-dev-$(date +%s).tgz"
          mv "${CHART_PACKAGE}" "${NEW_NAME}"
          helm push "${NEW_NAME}" "${ECR_URI}" --debug
