name: Helm Chart Bulk Publish to JFrog
run-name: Helm_bulk_jfrog_${{ inputs.environment }}_${{ inputs.region }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: dev
        options:
          - dev
          - qa
          - stg
          - prd

      region:
        type: choice
        description: 'AWS Region'
        required: true
        default: us-east-1
        options:
          - us-east-1
          - us-west-2

      charts_root:
        type: string
        description: 'Root folder of charts (e.g. charts)'
        required: true

      chart_version:
        type: string
        description: 'Helm Chart Version (e.g. 1.0.1)'
        required: true

jobs:
  publish-helm-charts:
    runs-on: ubuntu-latest

    env:
      JFROG_URL: ${{ vars.ARTIFACTORY }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      HELM_REPO_KEY: helm-charts-${{ inputs.environment }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh

      - name: Configure JFrog CLI
        run: |
          ./jfrog config add jfrog-server \
            --url="${JFROG_URL}" \
            --user="${JFROG_USERNAME}" \
            --password="${JFROG_PASSWORD}" \
            --interactive=false

      - name: Package and Upload All Helm Charts
        run: |
          mkdir -p packaged
          for chart_dir in ${{ inputs.charts_root }}/*; do
            if [ -d "$chart_dir" ] && [ -f "$chart_dir/Chart.yaml" ]; then
              chart_name=$(grep '^name:' "$chart_dir/Chart.yaml" | awk '{print $2}')
              echo "Packaging $chart_name..."
              helm dependency update "$chart_dir"
              helm lint "$chart_dir"
              helm package "$chart_dir" \
                --version "${{ inputs.chart_version }}" \
                --destination packaged

              chart_package="packaged/${chart_name}-${{ inputs.chart_version }}.tgz"
              echo "Uploading $chart_package to $HELM_REPO_KEY/${chart_name}-${{ inputs.chart_version }}/"
              ./jfrog rt upload "$chart_package" "${HELM_REPO_KEY}/${chart_name}-${{ inputs.chart_version }}/" --server-id=jfrog-server
            fi
          done

      - name: Reindex Helm Repository
        run: |
          ./jfrog rt helm-reindex "$HELM_REPO_KEY" --server-id=jfrog-server

      - name: Cleanup JFrog Config
        run: |
          ./jfrog config remove jfrog-server
